### ISSUE TITLE
public配下をNignxから配信していない

### ISSUE THREAD

**Issue by joe41203** [joe41203/terraform-k8s-rails-sample#1]
public配下をNignxから配信していないためパフォーマンスがよくない。

## 課題は何か？
Imageを複数選択していて、public配下マウントするときに空っぽになってしまう・・・
(現在はコメントアウト)

```yaml
      containers:
        - name: rails
          image: docker.io/kinjoyuji/webapp:latest
          imagePullPolicy: Always
          command: ['bundle', 'exec', 'puma', '-C', 'config/puma.rb']
          envFrom:
            - configMapRef:
                name: rails-config
          volumeMounts:
            - mountPath: /myapp/tmp/sockets
              name: web-sock
            # - mountPath: /myapp/public
            #   name: web-assets
        - name: nginx
          image: docker.io/kinjoyuji/nginx:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: nginx-port
          lifecycle:
            preStop:
              exec:
                # SIGTERM triggers a quick exit; gracefully terminate instead
                command: ['/usr/sbin/nginx', '-s', 'quit']
          volumeMounts:
            # - mountPath: /myapp/public
            #   name: web-assets
            #   readOnly: true
            - mountPath: /myapp/tmp/sockets
              name: web-sock
            - mountPath: /etc/nginx/
              name: nginx-conf
              readOnly: true
```

 ## 解決策
空マウントする前に、どこかのディレクトリに逃す？
